VERSION: '3.8'

services:
  fastapi_backend:
    build: .
    container_name: guesswho_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - db_data:/app/data
    environment:
      - RUNNING_ON_CONTAINER = true
      - DB_PATH=/app/data/guesswho.db
      - CORS_ORIGINS=https://guesswho.blazy.uk

volumes:
  db_data:
    name: guesswho_db_volume
