name: HypothesizeTheIndividual
description: "Create daily guessing games from your own images."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  auto_size_text: ^3.0.0
  auto_size_text_field: ^2.3.0
  file_picker: ^11.0.2
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.8
  flutter_staggered_grid_view: ^0.7.0
  http: ^1.6.0
  routemaster: ^1.1.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
